//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeShell.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeShell.Test.Resources.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;u_0_12&apos;].
        /// </summary>
        internal static string newTweetText {
            get {
                return ResourceManager.GetString("newTweetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@class=&apos;_5pbx userContent&apos;]/p.
        /// </summary>
        internal static string postedTweetText {
            get {
                return ResourceManager.GetString("postedTweetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;u_0_v&apos;]/div/div[5]/div/ul/li[2]/button.
        /// </summary>
        internal static string postNewTweetButton {
            get {
                return ResourceManager.GetString("postNewTweetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;pagelet_welcome_box&apos;]/ul/li[1]/div/div/a.
        /// </summary>
        internal static string verifyAccountName {
            get {
                return ResourceManager.GetString("verifyAccountName", resourceCulture);
            }
        }
    }
}
